apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: v2ray-exporter
build:
  artifacts:
    - image: yetio/v2ray-exporter
      docker:
        buildArgs:
          ARCH: amd64
deploy:
  kustomize:
    paths:
      - k8s
